# Generated by Django 5.2.6 on 2025-09-22 02:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("a_app", "0002_wishlist_added_at_alter_wishlist_user_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="created_at",
            new_name="date_ordered",
        ),
        migrations.RenameField(
            model_name="orderitem",
            old_name="price_at_purchase",
            new_name="price",
        ),
        migrations.AddField(
            model_name="order",
            name="address",
            field=models.TextField(default="null"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="name",
            field=models.CharField(default="null", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="transaction_uuid",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Packed", "Packed"),
                    ("Getting ready for delivery", "Getting ready for delivery"),
                    ("Delivered", "Delivered"),
                ],
                default="Pending",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.PositiveIntegerField(),
        ),
    ]
